version: '3.4'

services:
  crazy-bike.buy:
    image: crazybikemaincr.azurecr.io/crazybike-buy:latest-9ee003eeffe7cd25bf57301f6c733099
    build:
      context: .
      dockerfile: Dockerfile.buy
    ports:
      - "7071:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASBConnectionString=<asb-connection-string>
  crazy.bike.assembler:
    image:  crazybikemaincr.azurecr.io/crazybike-assembler:latest-c71167105522103fcf8e499975927b37
    build:
      context: .
      dockerfile: Dockerfile.assembler
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASBConnectionString=<asb-connection-string>
  crazy.bike.shipper:
    image: crazybikemaincr.azurecr.io/crazybike-shipper:latest-cf146849c5762fb794d0ca4b4015a1b1
    build:
      context: .
      dockerfile: Dockerfile.shipper
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASBConnectionString=<asb-connection-string>
  