version: '3.4'

services:
  crazy-bike.buy:
    build:
      context: .
      dockerfile: ./CrazyBike.Buy/Dockerfile.buy
    ports:
      - "7071:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASBConnectionString=<asb-connection-string>
  crazy-bike.assembler:
    build:
      context: .
      dockerfile: ./CrazyBike.Assembler/Dockerfile.assembler
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASBConnectionString=<asb-connection-string>
  crazy-bike.shipper:
    build:
      context: .
      dockerfile: ./CrazyBike.Shipper/Dockerfile.shipper
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASBConnectionString=<asb-connection-string>
  